version: "3"

services:
    ngnix:
        image: nginx-proxy
        container_name: nginx-proxy
        build: ./src/nginx
        depends_on:
            - app
        volumes:
            - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
        restart: on-failure
    mysql:
        image: zendesk-chatops-db
        container_name: zendesk-chatops-db
        build: ./src/db
        environment:
            MYSQL_DATABASE: userdb
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: mysqluser
            MYSQL_PASSWORD: password
            DATABASE_HOST: mysql
    app:
        image: zendesk-chatops-app
        container_name: zendesk-chatops-app
        build: ./src
        environment:
            DATABASE_HOST: mysql
            MYSQL_PORT: 3306
            MYSQL_DATABASE: userdb
            MYSQL_USER: mysqluser
            MYSQL_PASSWORD: password
        depends_on:
            - mysql
        restart: on-failure
