# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: userdb
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: mysqluser
          MYSQL_PASSWORD: password
          DATABASE_HOST: mysql
        ports:
          - 3306

    steps:
    - uses: actions/checkout@v2
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        mysql version: '5.7'
        mysql database: 'userdb'
        mysql root password: 'password'
        mysql user: 'mysqluser'
        mysql password: 'password'
    - run: mysql -umysqluser -ppassword userdb < ./db/createTable.sql
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: npm ci
    - name: Run application
      run: npm run start
    - name: Run test
      run: npm test
